plugins:
  - jekyll-remote-theme

title: Mathematics for Software Engineering
description: Click <a href='/MSE1'>here</a> to return to the main page

markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true

baseurl: "/MSE1" # Add your repository name if necessary

defaults:
  - scope:
      path: "" # Applies to all files
    values:
      layout: "default"
