remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

title: Mathematics for Software Engineering
description: Click <a href='/MSE1'>here</a> to return to the main page

markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true

